<?php if ($this->isOnestepCheckoutAllowed()):?>
<button type="button" title="<?php echo $this->__('עברי לקופה') ?>" class="button btn-proceed-checkout btn-checkout<?php if (!$this->checkEnable()){ echo 'no-checkout'; }?>"<?php if (!$this->checkEnable()){ echo ' disabled="disabled" ';} ?> onclick="window.location='<?php echo $this->getOnestepCheckoutUrl() ?>';"><span><span><?php echo $this->__('עברי לקופה') ?></span></span></button>
<?php endif?>

