<?php
$_height = Mage::getStoreConfig('payment/icreditgateway/height');
$_width = Mage::getStoreConfig('payment/icreditgateway/width');
$_window_type = Mage::getStoreConfig('payment/icreditgateway/window_type');

?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.8.3.js')?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.fancybox-1.3.4.js')?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/jquery.fancybox-1.3.4.css')?>" media="all" />
<?php  if($_window_type =='popup'):?>
 <div id="popup_val" style="display:none;">
 <iframe src="<?php echo Mage::registry('mygateway_ul');?>" width="<?php echo $_width;?>px" height="<?php echo $_height;?>px" frameborder="0"></iframe>
</div>
<?php elseif($_window_type =='iframe'):?>
<div class="myframe" style="width:<?php echo $_width;?>px;  margin:0 auto;">    
<iframe src="<?php echo Mage::registry('mygateway_ul');?>" width="<?php echo $_width;?>px" height="<?php echo $_height;?>" frameborder="0"></iframe></div>
<?php endif;?>
<?php  if($_window_type=='popup'):?>
 <script type="text/javascript">
    jQuery(document).ready(function() {
    	var content = jQuery('#popup_val').html();
                    jQuery.fancybox({
                    'autoScale'     : 'true',
                    'autoDimensions': 'true',
                    'overlayShow'   : 'true',
                    'scrolling'     : 'no',
                    'content':content,
                    'onComplete': function() {
                        jQuery("#fancybox-wrap").css({'top':'30px', 'bottom':'auto'});
                       }
           
 		});
    });
</script>
<?php endif;?>
