<?php
   $redirectTo = Mage::getBaseUrl().'checkout/onepage/success/';
   $redirecturl = Mage::getStoreConfig('payment/icreditgateway/redirect_url');

   if($redirecturl == ''){ ?>
      <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.8.3.js')?>"></script>
      <script type="text/javascript">
         jQuery(document).ready(function () {
            window.top.location.href = "<?php echo $redirectTo; ?>";
         });
      </script>
   <?php }else{ ?>
      <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery-1.8.3.js')?>"></script>
      <script type="text/javascript">
         jQuery(document).ready(function () {
            window.top.location.href = "<?php echo $redirecturl; ?>";
         });   
      </script>
   <?php } ?>